<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.eci.aquaport</groupId>
    <artifactId>aquaport-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>piplup</module>
        <!-- Cuando avances descomentas los siguientes: -->
        <!-- <module>prinplup</module> -->
        <!-- <module>empoleon</module> -->
    </modules>
</project>